-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        col = {
            active_border = "rgba(8c9197AA)",
            inactive_border = "rgba(42474dAA)",
        },
    },
})

hl.config({
    misc = {
        background_color = "rgba(121415FF)",
    },
})

hl.plugin("hyprbars", function()
    -- Honestly idk if it works like css, but well, why not
    bar_text_font = { "Rubik", "Geist", "AR One Sans", "Reddit Sans", "Inter", "Roboto", "Ubuntu", "Noto Sans", "sans-serif" },
    bar_height = 30,
    bar_padding = 10,
    bar_button_padding = 5,
    bar_precedence_over_border = true,
    bar_part_of_window = true,
    bar_color = "rgba(121415FF)",
    col.text = "rgba(e2e2e5FF)",
    -- example buttons (R -> L)
    -- hyprbars-button = color, size, on-click
    hyprbars-button = { "rgb(e2e2e5)", 13, "󰖭", "hyprctl dispatch killactive" },
    hyprbars-button = { "rgb(e2e2e5)", 13, "󰖯", "hyprctl dispatch fullscreen 1" },
    hyprbars-button = { "rgb(e2e2e5)", 13, "󰖰", "hyprctl dispatch movetoworkspacesilent special" },
end)

hl.window_rule({
    name  = "bordercolor_rgba_a2c",
    match = {
        pinned = 1,
    },
    -- TODO: review rule: "bordercolor rgba(a2cbecAA) rgba(a2cbec77)"
})
