#!/bin/bash

chosen=$(find ~/Pictures/Wallpapers/ -type f | vicinae dmenu -p "Select a photo:")
#fullpath=$(find ~/Pictures/Wallpapers -type f | grep "/$chosen$")
python ~/.local/bin/wallpaper_change.py "$chosen"
