-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--exec-once = wayvibes ~/akko_lavender_purples/ -v 1

--exec-once = pkill hyprlax; hyprlax -d 0.5 $(cat ~/.cache/wallpaper/current)

--exec-once = hyprsunset

--exec-once = nm-applet --indicator &

--exec-once = blueman-applet &

--exec-once = steam -silent

--exec-once = hyprctl dispatch workspace 5

--exec-once = sleep 0.25 && hyprctl dispatch workspace 1

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("wl-clip-persist --clipboard regular")
	--hl.exec_cmd("wl-paste --type text --watch cliphist store")
	--hl.exec_cmd("wl-paste --type image --watch cliphist store")
	--hl.exec_cmd("waybar")
	hl.exec_cmd("easyeffects -w")
	hl.exec_cmd("QS_ICON_THEME=Tela-circle-dracula-dark quickshell")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("playerctld daemon")
	hl.exec_cmd("vicinae server")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("trash-empty 30")
	hl.exec_cmd("swaync")
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
	hl.exec_cmd("swayosd-server")
	--hl.exec_cmd("voxtype -q daemon")
	--	hl.exec_cmd(
	--		"gpu-screen-recorder -w screen -f 60 -a default_output -a 'default_output|default_input' -c mp4 -r 120 -o '/home/rvdxse/Videos'"
	--	)
	hl.exec_cmd("gsr-ui")
	hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
end)
