exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = waybar
exec-once = hypridle
exec-once = playerctld daemon
#exec-once = wayvibes ~/akko_lavender_purples/ -v 1
#exec-once = pkill hyprlax; hyprlax -d 0.5 $(cat ~/.cache/wallpaper/current)
exec-once = awww-daemon --namespace default
exec-once = hyprsunset
#exec-once = nm-applet --indicator &
exec-once = trash-empty 30
exec-once = swaync
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = swayosd-server
#exec-once = blueman-applet &
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
#exec-once = steam -silent
#exec-once = hyprctl dispatch workspace 5
#exec-once = sleep 0.25 && hyprctl dispatch workspace 1
