-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("EDITOR", "nvim")

hl.env("TERMINAL", "kitty")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

--env = LIBVA_DRIVER_NAME,nvidia

--env = __GLX_VENDOR_LIBRARY_NAME,nvidia

hl.env("XDG_MENU_PREFIX", "artix-")

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

--env = QT_STYLE_OVERRIDE,kvantum
