# Sourcing external configs
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/user_binds.conf
# Window rules from separate file (as per your original config)
source = ~/.config/hypr/windowrules.conf



layerrule { 
  name = swaync-control-center
  blur = true
  ignore_alpha = 0
  match:namespace = swaync-control-center
}
layerrule {
    name = swaync-notification-window
    ignore_alpha = 0
    blur = true
    animation = appleEase
    match:namespace = swaync-notification-window
  }

layerrule {
    name = swaync
    ignore_alpha = 0
    blur = true
    match:namespace = swaync
  }

# this was required to not overflow the blur

#layerrule = ignorezero, swaync-control-center
#layerrule = blur, swaync-notification-window

#layerrule = animation appleEase, swaync-control-center

#layerrule = blur, swaync


# HyprMod managed settings
source = /home/rvdxse/.config/hypr/hyprland-gui.conf
