-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: max-gamma = 150

hl.config({
    profile = {
        time = "7:30",
        identity = true,
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output

hl.config({
    profile = {
        time = "21:00",
        temperature = 5500,
        gamma = 0.8,
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output
