-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by HyprMod

hl.config({
    animations = {
        enabled = 1,
    },
})

hl.config({
    gestures = {
        workspace_swipe_invert = 1,
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = 1,
    },
})

-- Animations

hl.animation({ leaf = "global", enabled = true, speed = 8.0, style = 1 })

-- Autostart


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("AyuGram -startintray")
end)
