-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Sourcing external configs

-- source = ~/.config/hypr/monitors.conf -> requires manual conversion
local monitors = require("monitors")
-- TODO: convert ~/.config/hypr/monitors.conf to .lua and use require()

-- source = ~/.config/hypr/programs.conf -> requires manual conversion
local programs = require("programs")
-- TODO: convert ~/.config/hypr/programs.conf to .lua and use require()

-- source = ~/.config/hypr/env.conf -> requires manual conversion
local env = require("env")
-- TODO: convert ~/.config/hypr/env.conf to .lua and use require()

-- source = ~/.config/hypr/autostart.conf -> requires manual conversion
local autostart = require("autostart")
-- TODO: convert ~/.config/hypr/autostart.conf to .lua and use require()

-- source = ~/.config/hypr/appearance.conf -> requires manual conversion
local appearance = require("appearance")
-- TODO: convert ~/.config/hypr/appearance.conf to .lua and use require()

-- source = ~/.config/hypr/input.conf -> requires manual conversion
local input = require("input")
-- TODO: convert ~/.config/hypr/input.conf to .lua and use require()

-- source = ~/.config/hypr/keybinds.conf -> requires manual conversion
local keybinds = require("keybinds")
-- TODO: convert ~/.config/hypr/keybinds.conf to .lua and use require()

-- source = ~/.config/hypr/rules.conf -> requires manual conversion
local rules = require("rules")
-- TODO: convert ~/.config/hypr/rules.conf to .lua and use require()

-- source = ~/.config/hypr/user_binds.conf -> requires manual conversion
local user_binds = require("user_binds")
-- TODO: convert ~/.config/hypr/user_binds.conf to .lua and use require()

-- Window rules from separate file (as per your original config)

-- source = ~/.config/hypr/windowrules.conf -> requires manual conversion
local windowrules = require("windowrules")
-- TODO: convert ~/.config/hypr/windowrules.conf to .lua and use require()

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	blur = true,
	ignore_alpha = 0.5,
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	ignore_alpha = 0.5,
	blur = true,
	animation = "appleEase",
})

-- this was required to not overflow the blur

--layerrule = ignorezero, swaync-control-center

--layerrule = blur, swaync-notification-window

--layerrule = animation appleEase, swaync-control-center

--layerrule = blur, swaync

-- HyprMod managed settings

-- source = /home/rvdxse/.config/hypr/hyprland-gui.conf -> requires manual conversion
-- local hyprland_gui = require("hyprland_gui")
-- TODO: convert /home/rvdxse/.config/hypr/hyprland-gui.conf to .lua and use require()
