-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
	input = {
		kb_layout = "us, ru, ua",
		kb_options = "grp:alt_shift_toggle",
		force_no_accel = true,
		follow_mouse = 1,
		repeat_delay = 200,
		repeat_rate = 40,
		sensitivity = 0,
		touchpad = {
			natural_scroll = true,
			scroll_factor = 0.5,
			tap_to_click = true,
			disable_while_typing = false,
		},
	},
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

hl.gesture({ fingers = 3, direction = "pinchin", action = "float", "tile" })

-- TODO: manual review: gesture = 3, "pinchout", "float", "float"

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})
