input {
    kb_layout = us,ru,ua
    kb_options = grp:alt_shift_toggle
    force_no_accel = true
    follow_mouse = 1
    repeat_delay = 200
    repeat_rate = 40
    sensitivity = 0 
    
    touchpad {
        natural_scroll = true
        scroll_factor = 0.5
        tap-to-click = true
        disable_while_typing = false
    }
}

gesture = 3, horizontal, workspace
gesture = 3, pinchin,float,tile
gesture = 3, pinchout,float, float
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
