-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"

hl.bind(mainMod .. " + " .. "F1", hl.dsp.submap("hide"))

hl.bind(mainMod .. " + " .. "F1", hl.dsp.exec_cmd('swayosd-client --custom-message "Hotkeys Disabled"'))

hl.define_submap("hide", function()
	hl.bind(mainMod .. " + " .. "F1", hl.dsp.submap("reset"))
	hl.bind(mainMod .. " + " .. "F1", hl.dsp.exec_cmd('swayosd-client --custom-message "Hotkeys Enabled"'))
end)

hl.bind(mainMod .. " + " .. "equal", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 2.0"))

hl.bind("SUPER + SHIFT" .. " + " .. "minus", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1.0"))

hl.bind(mainMod .. " + " .. "F11", hl.dsp.window.fullscreen())

hl.bind("SUPER + SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("pgrep -x wlogout && pkill -x wlogout || wlogout"))

hl.bind("SUPER" .. " + " .. "N", hl.dsp.exec_cmd("obsidian"))

--hl.bind("SUPER" .. " + " .. "O", hl.dsp.window.set_prop("active opaque toggle"))

hl.bind("SUPER + O", hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", window = "active" }))

hl.bind("SUPER + SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("hyprpicker -a| wl-copy && wtype -M ctrl v -m ctrl"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.exec_cmd("hyprvoice toggle"))

hl.bind("SUPER + R", hl.dsp.exec_cmd("voxtype record start"))
hl.bind("SUPER + R", hl.dsp.exec_cmd("voxtype record stop"), { release = true })
--hl.bind(
--	mainMod .. " + " .. "V",
--	hl.dsp.exec_cmd(
--		"cliphist list| rofi -dmenu -display-columns 2| cliphist decode| wl-copy && wtype -M ctrl v -m ctrl"
--	)
--)
hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("vicinae vicinae://launch/clipboard/history?toggle=true"))

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("AyuGram"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("zen-browser"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("code"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.window.float())
hl.bind(mainMod .. " + CONTROL + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + CONTROL + down", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + CONTROL + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + CONTROL + right", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))

--hl.bind(
--	"ALT + F10",
--	hl.dsp.exec_cmd(
--		'killall -USR1 gpu-screen-recorder && notify-send -u normal "ShadowPlay" "Последние 2 минуты сохранены!"'
--	)
--)
--hl.bind(mainMod .. " + " .. "Space", hl.dsp.exec_cmd("vicinae toggle"))

--bindd = $mainMod, Space, Open app launcher, exec, $menu

-- lid closed -> lock the screen
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("loginctl lock-session"), { locked = true })

-- lid opened -> notify (just to test)
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("notify-send 'Welcome back'"), { locked = true })

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

hl.bind(mainMod .. " + " .. "semicolon", hl.dsp.layout("togglesplit"))

hl.bind(mainMod .. " + " .. "G", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("open-webapp https://claude.ai"))

hl.bind(mainMod .. " + " .. "Y", hl.dsp.exec_cmd("open-webapp https://youtube.com"))

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("$terminal -e lazydocker"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

--hl.bind(mainMod .. " + " .. "S", hl.dsp.window.move({ direction = "+0" }))

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind("Print", hl.dsp.exec_cmd("grimblast copy screen"))

hl.bind(
	mainMod .. " + " .. "Print",
	hl.dsp.exec_cmd(
		"grim -t ppm - | satty --filename - --output-filename ~/Pictures/Screenshots/$(date +'%Y%m%d-%H%M:%S').png --copy-command \"wl-copy\""
	)
)

-- Move focus

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

-- Switch workspaces

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "T",
	hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/wallpaper_change")
)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t -sw"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("pkill waybar; waybar"))

-- Move window to workspace

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind("CONTROL + SHIFT" .. " + " .. "Escape", hl.dsp.exec_cmd("kitty --class taskmgr -e btop"))

-- Scroll workspaces

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize (mouse)

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + " .. "Z", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "X", hl.dsp.window.resize(nil), { mouse = true })

-- Volume

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume +2"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume -2"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -t"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower"), { locked = true })

-- Media

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
