-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local terminal = "kitty"

local browser = "zen-browser"

local fileManager = "nautilus"

local menu = "rofi -show drun -show-icons -drun-display-format {name}"

local editor = "code"
