-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.window_rule({
	name = "pavucontrol-float",
	match = {
		class = "pavucontrol",
	},
	float = true,
	center = true,
	size = { 600, 400 },
})

hl.window_rule({
	name = "kitty-opacity",
	match = {
		class = "(.*(kitty).*)$",
	},
})

hl.window_rule({
	name = "virt",
	match = {
		class = "remote-viewer",
	},
	opacity = "1",
})

hl.window_rule({
	name = "task_manager",
	match = {
		class = "taskmgr",
	},
	float = true,
	size = { 1200, 800 },
	center = 1,
})

hl.window_rule({
	name = "sushi_float",
	match = {
		class = "org.gnome.NautilusPreviewer",
	},
	float = true,
	size = { 1200, 675 },
	center = 1,
	opacity = "1.0",
})

hl.window_rule({
	name = "floatshee",
	match = {
		class = "floatshee",
	},
	float = true,
	size = { 1200, 800 },
	center = 1,
	opacity = "0.8",
})

hl.window_rule({
	name = "satty-screenshot",
	match = {
		class = "com.gabm.satty",
	},
	opacity = "1",
	float = true,
	center = true,
	size = { 1200, 750 },
})

hl.window_rule({
	name = "qemu_opacity",
	match = {
		class = "qemu",
	},
	opacity = "1",
})

hl.window_rule({
	name = "youtube-opacity-override",
	match = {
		title = "(.*(YouTube).*)$",
	},
	opacity = "1",
})

hl.window_rule({
	name = "opaque-apps",
	match = {
		class = "(.*(Boxes|ONLYOFFICE|vlc|zoom|eog|steam|Clapper).*)$",
	},
	opacity = "1",
})

--windowrule {

--  name = kitty-saver-fullscreen

--  match:class = ^(kitty-saver)$

--

--  fullscreen = true

--}

-- Layer rules

--layerrule = ignorealpha 0.4, waybar

hl.layer_rule({
	match = {
		namespace = "waybar",
	},
	blur = true,
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "swayosd",
	},
	blur = true,
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	blur = true,
	ignore_alpha = 0.5,
	animation = "slide right",
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	blur = true,
	ignore_alpha = 0.5,
})

hl.layer_rule({
	match = {
		namespace = "rofi",
	},
	blur = true,
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "logout_dialog",
	},
	blur = true,
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "vicinae",
	},
	blur = true,
	ignore_alpha = 0,
})

hl.layer_rule({
	match = {
		namespace = "gsr-ui",
	},
	blur = true,
	ignore_alpha = 0,
})

hl.window_rule({
	name = "suppress-maximize",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland

hl.window_rule({
	name = "xwayland-drag-fix",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})
