bind = SUPER, H, exec, kitty -e htop # Added via script
bind = SUPER_SHIFT, R, exec, kitty -e ssh VPS # Added via script
bind = SUPER, L, exec, hyprlock # Added via script
bind = SUPER, U, exec, kitty --class taskmgr -e share file # Added via script
bind = SUPER, I, exec, kitty --class taskmgr -e share folder
