-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Added via script

-- hl.bind("SUPER + SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

-- Added via script

hl.bind("SUPER" .. " + " .. "U", hl.dsp.exec_cmd("kitty --class taskmgr -e share file"))

-- Added via script

hl.bind("SUPER" .. " + " .. "I", hl.dsp.exec_cmd("kitty --class taskmgr -e share folder"))
