-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Sizes for floating popups

hl.window_rule({
	name = "floating-size",
	match = {
		float = true,
	},
	size = { "<85%", "<95%" },
})

hl.window_rule({
	name = "common-popups-float",
	match = {
		tag = "common-popups",
	},
	float = true,
	size = { "<60%", "<90%" },
})

-- Fix file chooser dialogs opening off-screen

hl.window_rule({
	name = "portal-dialogs-float",
	match = {
		tag = "portal-dialogs",
	},
	float = true,
	center = true,
})

-- Only add the Core applications here

hl.window_rule({
	name = "satty-float",
	match = {
		class = "^(com.gabm.satty)$",
	},
	float = true,
})

hl.window_rule({
	name = "dolphin-progress-float",
	match = {
		class = "^(org.kde.dolphin)$",
		title = "^(Progress Dialog — Dolphin)$",
	},
	float = true,
})

hl.window_rule({
	name = "dolphin-copying-float",
	match = {
		class = "^(org.kde.dolphin)$",
		title = "^(Copying — Dolphin)$",
	},
	float = true,
})

hl.window_rule({
	name = "firefox-about-float",
	match = {
		title = "^(About Mozilla Firefox)$",
	},
	float = true,
})

hl.window_rule({
	name = "firefox-focus",
	match = {
		class = "^(firefox|Firefox)$",
	},
	focus_on_activate = true,
})

hl.window_rule({
	name = "zen-focus",
	match = {
		class = "^(zen|Zen)$",
	},
	focus_on_activate = true,
})

hl.window_rule({
	name = "top-float",
	match = {
		initial_title = "^(top)$",
	},
	float = true,
})

hl.window_rule({
	name = "btop-float",
	match = {
		initial_title = "^(btop)$",
	},
	float = true,
})

hl.window_rule({
	name = "htop-float",
	match = {
		initial_title = "^(htop)$",
	},
	float = true,
})

--windowrule {

--  name = vlc-float

--  match:class = ^(vlc)$

--

--  float = true

--}

hl.window_rule({
	name = "kvantum-float",
	match = {
		class = "^(kvantummanager)$",
	},
	float = true,
})

hl.window_rule({
	name = "qt5ct-float",
	match = {
		class = "^(qt5ct)$",
	},
	float = true,
})

hl.window_rule({
	name = "qt6ct-float",
	match = {
		class = "^(qt6ct)$",
	},
	float = true,
})

hl.window_rule({
	name = "nwg-look-float",
	match = {
		class = "^(nwg-look)$",
	},
	float = true,
})

hl.window_rule({
	name = "nwg-displays-float",
	match = {
		class = "^(nwg-displays)$",
	},
	float = true,
})

hl.window_rule({
	name = "ark-float",
	match = {
		class = "^(org.kde.ark)$",
	},
	float = true,
})

hl.window_rule({
	name = "pavucontrol-float",
	match = {
		class = "^(org.pulseaudio.pavucontrol)$",
	},
	float = true,
})

hl.window_rule({
	name = "blueman-float",
	match = {
		class = "^(blueman-manager)$",
	},
	float = true,
})

hl.window_rule({
	name = "nm-applet-float",
	match = {
		class = "^(nm-applet)$",
	},
	float = true,
})

hl.window_rule({
	name = "nm-editor-float",
	match = {
		class = "^(nm-connection-editor)$",
	},
	float = true,
})

hl.window_rule({
	name = "polkit-float",
	match = {
		class = "^(org.kde.polkit-kde-authentication-agent-1)$",
	},
	float = true,
})

hl.window_rule({
	name = "onlyoffice-opacity",
	match = {
		class = "^(ONLYOFFICE)$",
	},
	opacity = "1",
})

-- Common popups tags

hl.window_rule({
	name = "tag-open-file",
	match = {
		initial_title = "^(Open File)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-choose-files",
	match = {
		title = "^(Choose Files)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-save-as",
	match = {
		title = "^(Save As)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-confirm-replace",
	match = {
		title = "^(Confirm to replace files)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-file-progress",
	match = {
		title = "^(File Operation Progress)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-xdg-gtk",
	match = {
		class = "^([Xx]dg-desktop-portal-gtk)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-open",
	match = {
		title = "^(Open)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-auth",
	match = {
		title = "^(Authentication Required)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-add-folder",
	match = {
		title = "^(Add Folder to Workspace)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-file-upload",
	match = {
		title = "^(File Upload)(.*)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-wallpaper",
	match = {
		title = "^(Choose wallpaper)(.*)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-library",
	match = {
		title = "^(Library)(.*)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-dialog-class",
	match = {
		class = "^(.*dialog.*)$",
	},
	tag = "+common-popups",
})

hl.window_rule({
	name = "tag-dialog-title",
	match = {
		title = "^(.*dialog.*)$",
	},
	tag = "+common-popups",
})

-- Portal dialogs tags

hl.window_rule({
	name = "tag-portal-hyprland",
	match = {
		class = "^(org.freedesktop.impl.portal.desktop.hyprland)$",
	},
	tag = "+portal-dialogs",
})

hl.window_rule({
	name = "tag-portal-gtk",
	match = {
		class = "^(org.freedesktop.impl.portal.desktop.gtk)$",
	},
	tag = "+portal-dialogs",
})

hl.window_rule({
	name = "tag-portal-xdg",
	match = {
		class = "^([Xx]dg-desktop-portal-gtk)$",
	},
	tag = "+portal-dialogs",
})

-- Disable border and blur for gtk apps

hl.window_rule({
	name = "xdg-noborder",
	match = {
		class = "^(Xdg-desktop-portal-gtk)$",
	},
	border_size = 0,
	no_blur = true,
})

hl.window_rule({
	name = "file-upload-noborder",
	match = {
		title = "^(File Upload)$",
	},
	border_size = 0,
	no_blur = true,
})
