-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This configuration is generated by matugen

-- Changing these variables with matugen still enabled will overwrite them.

local text_color = "rgba(c9e6ffFF)"

local entry_background_color = "rgba(001e2f11)"

local entry_border_color = "rgba(8c919755)"

local entry_color = "rgba(c9e6ffFF)"

local font_family = "Rubik"

local font_family_clock = "Space Grotesk DemiBold"

local font_material_symbols = "Material Symbols Rounded"

local background_image = "/home/rvdxse/Pictures/Wallpapers/a_house_with_a_chair_and_a_bicycle.jpg"
